name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  complexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Install gocognit
        run: go install github.com/uudashr/gocognit/cmd/gocognit@latest
      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Run gocognit
        run: gocognit -over 10 .
      - name: Run gocyclo
        run: gocyclo -over 10 .

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run go vet
        run: go vet ./...
      - name: Run staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run unit tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5
